# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0002_auto_20170511_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='_business_value',
            new_name='business_value',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='_list',
            new_name='list',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='_story_points',
            new_name='story_points',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='_name',
            new_name='name',
        ),
    ]
